### ISSUE TITLE
Update git2go dependency to version 33

### ISSUE THREAD

**Issue by yusdacra** [b4nst/turbogit#104]
Hello! I'm maintaining `turbogit` on [nixpkgs](https://github.com/NixOS/nixpkgs). Currently it doesn't build because of a `libgit2` version mismatch with `git2go`. Current `git2go` version depends on `v1.1` of `libgit2`, but nixpkgs contains a `v1.3` version of `libgit2`. The version of `git2go` that supports `v1.3` of `libgit2` seems to be `v33`, as described [on git2go's readme](https://github.com/libgit2/git2go). So I would like to request a dependency update and a minor release if possible to fix this issue.

<details>
<summary>Build log</summary>
<pre><code>@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/vpl3zlpfg2i73jr651x6wnpg5i37b1y2-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building subPackage ./.
internal/unsafeheader
internal/cpu
runtime/internal/atomic
runtime/internal/sys
math/bits
runtime/internal/math
unicode/utf8
internal/race
sync/atomic
internal/bytealg
math
unicode
golang.org/x/sys/internal/unsafeheader
github.com/b4nst/turbogit/pkg/constants
crypto/internal/subtle
crypto/subtle
runtime
unicode/utf16
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
runtime/cgo
golang.org/x/crypto/internal/subtle
encoding
container/list
vendor/golang.org/x/crypto/internal/subtle
golang.org/x/text/encoding/internal/identifier
image/color
github.com/rivo/uniseg
internal/reflectlite
sync
internal/testlog
internal/singleflight
math/rand
errors
sort
io
internal/oserror
strconv
syscall
path
bytes
strings
golang.org/x/text/transform
reflect
golang.org/x/text/width
bufio
regexp/syntax
github.com/kballard/go-shellquote
hash
crypto
internal/syscall/unix
time
internal/syscall/execenv
crypto/internal/randutil
vendor/golang.org/x/net/dns/dnsmessage
regexp
internal/poll
io/fs
context
internal/fmtsort
encoding/binary
os
crypto/hmac
crypto/rc4
golang.org/x/crypto/blowfish
hash/crc32
vendor/golang.org/x/crypto/hkdf
golang.org/x/sys/unix
crypto/sha1
crypto/cipher
fmt
path/filepath
crypto/aes
io/ioutil
os/exec
net/url
text/template/parse
github.com/AlecAivazis/survey/v2/terminal
github.com/araddon/dateparse
github.com/mattn/go-isatty
golang.org/x/term
github.com/mattn/go-colorable
github.com/hpcloud/golor
text/template
github.com/mgutz/ansi
github.com/imdario/mergo
math/big
crypto/des
crypto/sha512
github.com/b4nst/turbogit/pkg/format
crypto/ed25519/internal/edwards25519
crypto/md5
github.com/AlecAivazis/survey/v2/core
crypto/sha256
encoding/hex
encoding/base64
encoding/pem
net
github.com/AlecAivazis/survey/v2
golang.org/x/crypto/chacha20
crypto/rand
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/ed25519
crypto/rsa
vendor/golang.org/x/crypto/cryptobyte
crypto/x509/pkix
golang.org/x/crypto/curve25519/internal/field
golang.org/x/crypto/ed25519
golang.org/x/crypto/poly1305
golang.org/x/crypto/curve25519
golang.org/x/crypto/ssh/internal/bcrypt_pbkdf
log
crypto/ecdsa
github.com/whilp/git-urls
encoding/json
github.com/fatih/structs
github.com/google/go-querystring/query
github.com/pkg/errors
github.com/trivago/tgo/treflect
mime
github.com/trivago/tgo/tcontainer
mime/quotedprintable
compress/flate
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/sys/cpu
vendor/golang.org/x/crypto/curve25519
compress/gzip
vendor/golang.org/x/text/transform
vendor/golang.org/x/crypto/chacha20poly1305
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/net/http2/hpack
vendor/golang.org/x/text/secure/bidirule
net/http/internal
github.com/fatih/color
flag
vendor/golang.org/x/net/idna
github.com/briandowns/spinner
golang.org/x/text/encoding
github.com/gdamore/encoding
github.com/gdamore/tcell/v2/terminfo
database/sql/driver
github.com/mattn/go-runewidth
github.com/gdamore/tcell/v2/terminfo/a/ansi
github.com/gdamore/tcell/v2/terminfo/v/vt100
github.com/gdamore/tcell/v2/terminfo/v/vt102
github.com/gdamore/tcell/v2/terminfo/v/vt220
github.com/gdamore/tcell/v2/terminfo/x/xterm
github.com/gdamore/tcell/v2/terminfo/dynamic
github.com/gdamore/tcell/v2/terminfo/a/aixterm
github.com/gdamore/tcell/v2/terminfo/base
github.com/gdamore/tcell/v2/terminfo/a/alacritty
github.com/gdamore/tcell/v2/terminfo/b/beterm
github.com/gdamore/tcell/v2/terminfo/c/cygwin
github.com/gdamore/tcell/v2/terminfo/d/dtterm
github.com/gdamore/tcell/v2/terminfo/e/emacs
github.com/gdamore/tcell/v2/terminfo/f/foot
github.com/gdamore/tcell/v2/terminfo/g/gnome
github.com/gdamore/tcell/v2/terminfo/h/hpterm
github.com/gdamore/tcell/v2/terminfo/k/konsole
github.com/gdamore/tcell/v2/terminfo/k/kterm
github.com/gdamore/tcell/v2/terminfo/l/linux
github.com/gdamore/tcell/v2/terminfo/p/pcansi
github.com/gdamore/tcell/v2/terminfo/r/rxvt
github.com/gdamore/tcell/v2/terminfo/s/screen
github.com/gdamore/tcell/v2/terminfo/s/simpleterm
github.com/gdamore/tcell/v2/terminfo/s/sun
github.com/gdamore/tcell/v2/terminfo/t/termite
github.com/gdamore/tcell/v2/terminfo/t/tmux
github.com/gdamore/tcell/v2/terminfo/v/vt320
github.com/gdamore/tcell/v2/terminfo/v/vt400
github.com/gdamore/tcell/v2/terminfo/v/vt420
github.com/gdamore/tcell/v2/terminfo/v/vt52
github.com/gdamore/tcell/v2/terminfo/w/wy50
github.com/gdamore/tcell/v2/terminfo/w/wy60
github.com/gdamore/tcell/v2/terminfo/w/wy99_ansi
github.com/gdamore/tcell/v2/terminfo/x/xfce
github.com/gdamore/tcell/v2/terminfo/x/xterm_kitty
github.com/gdamore/tcell/v2/terminfo/x/xterm_termite
github.com/lucasb-eyer/go-colorful
os/signal
github.com/gdamore/tcell/v2/terminfo/extended
github.com/ktr0731/go-fuzzyfinder/scoring
github.com/nsf/termbox-go
github.com/ktr0731/go-fuzzyfinder/matching
github.com/gdamore/tcell/v2
golang.org/x/time/rate
github.com/blang/semver/v4
encoding/csv
crypto/x509
net/textproto
vendor/golang.org/x/net/http/httpproxy
github.com/spf13/pflag
mime/multipart
vendor/golang.org/x/net/http/httpguts
github.com/ktr0731/go-fuzzyfinder
text/tabwriter
github.com/dgrijalva/jwt-go
golang.org/x/crypto/ssh
crypto/tls
github.com/spf13/cobra
github.com/libgit2/git2go/v31
net/http/httptrace
# github.com/libgit2/git2go/v31
vendor/github.com/libgit2/git2go/v31/Build_system_dynamic.go:11:3: error: #error "Invalid libgit2 version; this git2go supports libgit2 between v1.1.0 and v1.1.0"
   11 | # error "Invalid libgit2 version; this git2go supports libgit2 between v1.1.0 and v1.1.0"
      |   ^~~~~
net/http
golang.org/x/net/context/ctxhttp
github.com/hashicorp/go-cleanhttp
github.com/andygrunwald/go-jira
golang.org/x/oauth2/internal
github.com/hashicorp/go-retryablehttp
golang.org/x/oauth2
github.com/xanzy/go-gitlab</code></pre>
</details>

**Comment by b4nst** [comment]
Thanks for the report, and sorry for the lag. Currently working on the v33 upgrade 🙂
