### ISSUE TITLE
[BUG] Slowness issue on large repos

### ISSUE THREAD

**Issue by thibaut-lo** [b4nst/turbogit#20]
## Describe the bug

I had to Ctrl+C to take back control. The Action was performed correctly but I didn't have the hand back on the terminal
![image](https://user-images.githubusercontent.com/66995824/84885208-02178b80-b093-11ea-9a4a-6f07932b51fc.png)

## To Reproduce

**Steps**

* Enter `tug branch fix repair broken element-ui cascader `           
I waited for the command to execute and enter another command. I coudn't take back control without Ctrl+C. The branch was created anyhow                                                                                                                                                
**Expected behavior**

**Actual behavior**

* The shell prompt shall appear again at the end.

## Versions

 - *tug*:
```
Version:	1.1.0			
Go version:	go1.14.3		
Git commit:	5662855			
Built:		2020-05-31T17:22:36Z	
OS/Arch:	linux/386%     
```

 - *OS*: Ubuntu 18.04.4 LTS

**Comment by b4nst** [comment]
It seems to appear on heavy repositories (in terms of number of files / history). But eventually the command succeed and returns. Would it be possible for you to create a branch and let it run to see if it returns eventually (like running in Screen or another shell tab). That way we could confirm this is indeed the bug you're facing.

**Comment by thibaut-loftorbital** [comment]
@b4nst : I confirm it **does** finish after some times (beyond 10 secs) and that the bug is more a slowness issue.

**Comment by thibaut-lo** [comment]
This also applies for `tug commit`

**Comment by b4nst** [comment]
Does git itself is slow or is it just tug ? (`git commit -m 'the message'`)

**Comment by thibaut-lo** [comment]
Tug commit a few secs each time while git commit is superfast (a few ms)

**Comment by b4nst** [comment]
Thanks, gonna investigate

**Comment by thibaut-lo** [comment]
Also slow in Mac => git repo size seems to be the bug's origin
