### ISSUE TITLE
[FEAT] Support issues/tickets linked to the feature branch

### ISSUE THREAD

**Issue by nikolay** [b4nst/turbogit#50]
**Is your feature request related to a problem? Please describe.**
We use Jira and suffix commits with the ticket number, i.e. `feat: commit (DEV-0123)`, and also prefix the branch name with the ticket ID, i.e. `feat/dev-0123-commit`.

**Describe the solution you'd like**
We would like to see GitHub issues, Jira tickets, and others natively supported.

**Comment by b4nst** [comment]
Definitely useful (for us too). FYI I'm gonna first finish the refactor to `git2go` (for performance reasons) adding more unit tests in the same time. Then back to features, and this one is quite top priority for me. I want to be able to also integrate it to branch creation and probably further down (PR/MR, etc...).
First integrations planned: Jira, GitHub and GitLab
